
# Copyright (C) 2014-2020 NXP Semiconductors, All Rights Reserved.
# Copyright 2020 GOODIX 
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License version 2 as
#published by the Free Software Foundation.

# make sure that the environment variables ARCH and CROSS_COMPILE
# are set for your architecture and cross compiler.
# And that KDIR points to the kernel to build against.
#
# e.g.:
# export ARCH=arm
# export CROSS_COMPILE=arm-linux-gnueabihf-
# export KDIR=../linux


# In case of out of tree build, build as a module
# (when build inside kernel we will not enter this directory and this will have no effect)
ifeq ($(CONFIG_SND_SOC_TFA9874),)
CONFIG_SND_SOC_TFA9874 := m
endif

ifneq ($(KERNELRELEASE),)

EXTRA_CFLAGS += -I$(src)/inc
EXTRA_CFLAGS += -Werror

ifeq ($(CONFIG_MACH_ASUS_X00T),y)
EXTRA_CFLAGS += -DTFA9874_NONDSP_STEREO
endif

obj-$(CONFIG_SND_SOC_TFA9874) := snd-soc-tfa9874.o

snd-soc-tfa9874-objs += src/tfa98xx.o
snd-soc-tfa9874-objs += src/tfa_container.o
snd-soc-tfa9874-objs += src/tfa_dsp.o
snd-soc-tfa9874-objs += src/tfa_init.o

else

MAKEARCH := $(MAKE) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE)

all:
	$(MAKEARCH) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKEARCH) -C $(KDIR) M=$(PWD) clean
	rm -f $(snd-soc-tfa9874-objs)

endif

subdir-ccflags-y := $(call cc-disable-warning, enum-conversion)
